#include "Bureaucrat.hpp"
#include "AForm.hpp"
#include "ShrubberyCreationForm.hpp"
#include "RobotomyRequestForm.hpp"
#include "PresidentialPardonForm.hpp"
#include <ctime>
#include <cstdlib>

/**
 * @brief   std::srand(std::time(NULL));
 * * Initialize the random number generator seed.
 * * By using the current system time (std::time(NULL)), we ensure that 
 * the random sequences generated by std::rand() differ every time the 
 * program is executed. This is essential for the 50% success rate logic 
 * in the RobotomyRequestForm.
 * 
 * @brief	Understanding Seeds and srand:
 * * Seed: A starting value used by a pseudo-random number generator 
 * to produce a sequence of numbers. 
 * * srand(): The function used to set the 'seed'. By using the current 
 * time as a seed, we ensure the random sequence starts at a different 
 * point during each program execution, making std::rand() unpredictable.
 */
int main()
{
	std::srand(std::time(NULL));
	std::cout << "=== Basic Test ===\n\n";

	Bureaucrat boss("boss", 1);
	Bureaucrat director("director", 20);
	ShrubberyCreationForm shu("shu");
	
	std::cout << boss << "\n" << director << "\n" << shu << "\n";

	std::cout << std::endl;
	director.signForm(shu);
	shu.beSigned(boss);
	shu.execute(boss); //will create a file
	
	std::cout << std::endl;

	RobotomyRequestForm robot("robot");
	std::cout << robot << "\n";
	boss.executeForm(robot);
	
	robot.beSigned(boss);
	robot.execute(boss);
	robot.execute(boss);
	robot.execute(boss);


	std::cout << std::endl;

	director.executeForm(robot);
	std::cout << std::endl;


	PresidentialPardonForm President("President");
	std::cout << President << "\n";

	director.executeForm(President);
	President.beSigned(boss);
	President.execute(boss);
	director.executeForm(President);


	std::cout << "\n=== Exception Test ===\n\n";

	Bureaucrat npc("npc", 150);

	try
	{
		President.execute(npc);

	}
	catch(const std::exception& e)
	{
		std::cerr << e.what() << '\n';
	}

	try
	{
		robot.execute(npc);

	}
	catch(const std::exception& e)
	{
		std::cerr << e.what() << '\n';
	}
	
	try
	{
		shu.execute(npc);

	}
	catch(const std::exception& e)
	{
		std::cerr << e.what() << '\n';
	}

	return 0;
}
