#ifndef ITER_HPP
# define ITER_HPP

#include <iostream>

/**
 * @brief Uses multiple template parameters for maximum flexibility.
 * * By decoupling the element type 'T' from the callable type 'F', the compiler 
 * automatically deduces the exact signature of 'func' during instantiation.
 * * Whether 'F' is a function taking a non-const reference (void(*)(T&)) or 
 * a const reference (void(*)(const T&)), the compiler generates a 
 * specialized version of 'iter' for that specific combination.
 * 
 * @brief The template parameter 'F' is generic, allowing it to match 
 * various "callable" entities:
 * * 1. Regular Functions: Standard functions like 'void print(int& n)'.
 * * 2. Function Pointers: Variables that store the address of a function.
 * * 3. Functors (Function Objects): Instances of a class that overloads the 
 * 'operator()' to behave like a function.
 * * 4. Instantiated Function Templates: Specific versions of a template 
 * generated by the compiler (e.g., 'display<int>').
 * * This approach utilizes "compile-time polymorphism," ensuring that as 
 * long as the syntax 'func(array[i])' is valid, the code will compile and 
 * run efficiently.
 */
template <typename T, typename F>
void    iter(T* array, const size_t length, F func)
{
    if (!array)
        return;
    for (size_t i = 0; i < length; i++)
        func(array[i]);
}

#endif