[mysqld]

bind-address = 0.0.0.0

port = 3306

datadir = /var/lib/mysql

# Sets the default character encoding to utf8mb4 which supports emojis 
character-set-server = utf8mb4
#unicode_ci means it follows Unicode rules and is case-insensitive 
collation-server = utf8mb4_unicode_ci

# Disables the internal host cache. In Docker, container IPs change frequently, 
# so caching hostnames can cause stale/wrong results. 
skip-host-cache
# Faster connections, no DNS lookups
skip-name-resolve

max_connections = 100

log_error = /var/log/mysql/error.log
